
name: docker7

on:
  push:
    branches:
      - master
    paths:
      - docker/7/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          args: |
            cd docker/7
            docker build -t docker.pkg.github.com/anzerr/node.docker/node.docker:7 . &&
            docker push docker.pkg.github.com/anzerr/node.docker/node.docker:7
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          args: |
            cd docker/7
            docker build -t anzerr/node:7 . &&
            docker push anzerr/node:7
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          args: |
            cd docker/7/build
            docker build -t docker.pkg.github.com/anzerr/node.docker/node.docker:build-7 . &&
            docker push docker.pkg.github.com/anzerr/node.docker/node.docker:build-7
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          args: |
            cd docker/7/build
            docker build -t anzerr/node:build-7 . &&
            docker push anzerr/node:build-7
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          args: |
            cd docker/7/slim
            docker build -t docker.pkg.github.com/anzerr/node.docker/node.docker:slim-7 . &&
            docker push docker.pkg.github.com/anzerr/node.docker/node.docker:slim-7
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          args: |
            cd docker/7/slim
            docker build -t anzerr/node:slim-7 . &&
            docker push anzerr/node:slim-7