
name: docker10

on:
  push:
    paths:
      - docker/10/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          args: |
            cd docker/10
            docker build -t docker.pkg.github.com/anzerr/node.docker/node.docker:10 . &&
            docker push docker.pkg.github.com/anzerr/node.docker/node.docker:10
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          args: |
            cd docker/10
            docker build -t anzerr/node:10 . &&
            docker push anzerr/node:10
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          args: |
            cd docker/10/slim
            docker build -t docker.pkg.github.com/anzerr/node.docker/node.docker:slim-10 . &&
            docker push docker.pkg.github.com/anzerr/node.docker/node.docker:slim-10
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          args: |
            cd docker/10/slim
            docker build -t anzerr/node:slim-10 . &&
            docker push anzerr/node:slim-10