
name: docker14

on:
  push:
    paths:
      - docker/14/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          args: |
            cd docker/14
            docker build -t docker.pkg.github.com/anzerr/node.docker/node.docker:14 . &&
            docker push docker.pkg.github.com/anzerr/node.docker/node.docker:14
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          args: |
            cd docker/14
            docker build -t anzerr/node:14 . &&
            docker push anzerr/node:14
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          args: |
            cd docker/14/build
            docker build -t docker.pkg.github.com/anzerr/node.docker/node.docker:build-14 . &&
            docker push docker.pkg.github.com/anzerr/node.docker/node.docker:build-14
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          args: |
            cd docker/14/build
            docker build -t anzerr/node:build-14 . &&
            docker push anzerr/node:build-14
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          args: |
            cd docker/14/slim
            docker build -t docker.pkg.github.com/anzerr/node.docker/node.docker:slim-14 . &&
            docker push docker.pkg.github.com/anzerr/node.docker/node.docker:slim-14
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          args: |
            cd docker/14/slim
            docker build -t anzerr/node:slim-14 . &&
            docker push anzerr/node:slim-14